name: ðŸŽ² Generate Test Data

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  generate-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: ðŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: ðŸŽ² Generate test data
        run: |
          python ml_training/scripts/generate_test_data.py
      
      - name: ðŸ’¾ Commit test data
        run: |
          git config user.name "Test Data Bot"
          git config user.email "test-bot@footy-oracle.com"
          git add shared/ml_outputs/*.json
          git diff --staged --quiet || git commit -m "ðŸŽ² Generate test data - $(date +%Y-%m-%d)"
          git push
      
      - name: âœ… Summary
        run: |
          echo "## ðŸŽ² Test Data Generated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** $(date +%Y-%m-%d)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "âœ… predictions.json updated" >> $GITHUB_STEP_SUMMARY
          echo "âœ… golden_bets.json updated" >> $GITHUB_STEP_SUMMARY
          echo "âœ… value_bets.json updated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "ðŸš€ Frontend should now display data!" >> $GITHUB_STEP_SUMMARY
