name: 📅 Update Fixtures - Live Data

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours
  workflow_dispatch:        # Manual trigger

jobs:
  update-fixtures:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      
      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: 📦 Install dependencies
        run: |
          pip install requests python-dotenv
      
      - name: 🔍 Validate API Key Secret
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: |
          if [ -z "$API_FOOTBALL_KEY" ]; then
            echo "❌ CRITICAL ERROR: API_FOOTBALL_KEY secret is NOT set in GitHub!"
            exit 1
          else
            echo "✅ API_FOOTBALL_KEY secret exists (length: ${#API_FOOTBALL_KEY})"
          fi
      
      - name: 🧪 Comprehensive API Test
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: |
          python -c "
          import os
          import requests
          import json
          
          API_KEY = os.environ['API_FOOTBALL_KEY']
          
          print('🔍 Testing all possible API configurations...')
          print(f'API Key: {API_KEY[:8]}...{API_KEY[-4:]}')
          print(f'Key length: {len(API_KEY)}')
          print()
          
          # Test configurations
          configs = [
              {
                  'name': 'RapidAPI Format',
                  'url': 'https://v3.football.api-sports.io/fixtures',
                  'headers': {
                      'x-rapidapi-key': API_KEY,
                      'x-rapidapi-host': 'v3.football.api-sports.io'
                  },
                  'params': {'date': '2025-11-27'}
              },
              {
                  'name': 'Direct API-Sports (x-apisports-key)',
                  'url': 'https://v3.football.api-sports.io/fixtures',
                  'headers': {
                      'x-apisports-key': API_KEY
                  },
                  'params': {'date': '2025-11-27'}
              },
              {
                  'name': 'Direct API-Sports (x-api-key)',
                  'url': 'https://v3.football.api-sports.io/fixtures',
                  'headers': {
                      'x-api-key': API_KEY
                  },
                  'params': {'date': '2025-11-27'}
              }
          ]
          
          working_config = None
          
          for config in configs:
              print(f'\\n📡 Testing: {config[\"name\"]}')
              print(f'URL: {config[\"url\"]}')
              print(f'Headers: {list(config[\"headers\"].keys())}')
              
              try:
                  response = requests.get(
                      config['url'],
                      headers=config['headers'],
                      params=config['params'],
                      timeout=10
                  )
                  
                  print(f'Status Code: {response.status_code}')
                  
                  if response.status_code == 200:
                      data = response.json()
                      fixtures = data.get('response', [])
                      print(f'✅ SUCCESS! Found {len(fixtures)} fixtures')
                      print(f'API Response Keys: {list(data.keys())}')
                      if 'errors' in data and data['errors']:
                          print(f'Errors: {data[\"errors\"]}')
                      working_config = config
                      break
                  else:
                      print(f'❌ Failed')
                      print(f'Response: {response.text[:300]}')
                      
              except Exception as e:
                  print(f'❌ Exception: {str(e)}')
          
          if not working_config:
              print('\\n❌ ALL CONFIGURATIONS FAILED!')
              print('\\nYour API key might be:')
              print('1. Invalid or expired')
              print('2. Not activated')
              print('3. Rate limited')
              print('4. From a different API provider')
              exit(1)
          else:
              print(f'\\n✅ Working configuration: {working_config[\"name\"]}')
              
              # Save working config for next steps
              with open('/tmp/api_config.json', 'w') as f:
                  json.dump(working_config, f)
          "
